project:
  type: default
  output-dir: docs

book:
  title: "R Vignettes for Computational Social Science"
  author: "Daulton Selke"
  date: "9/10/2025"
  sidebar:
    title: " "
    logo: embeddings.jpg

  chapters:
    - index.qmd
    - usajobs_embeddings.qmd



bibliography: references.bib

format:
  html:
    theme:
      - darkly
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

